name: Backup

on:
  schedule:
    - cron: '21 15 * * *'  # Schedule: Runs at 15:21 UTC every day
  push:
    branches: [main, dev] 

jobs:
  backup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      URI: ${{ secrets.URI }}
      BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
      ENDPOINT: ${{ secrets.ENDPOINT }}
      ENV_TEST: ${{ secrets.ENV_TEST }}

    steps:
      - name: Checkout Code  
        uses: actions/checkout@v2
        with:
          path: backups  # Ensures code is checked out into the 'backups' folder

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install mongo-tools
        run: |
          echo "Installing MongoDB tools..."
          sudo wget https://fastdl.mongodb.org/tools/db/mongodb-database-tools-debian92-x86_64-100.3.1.deb 
          sudo apt install ./mongodb-database-tools-*.deb
          echo "MongoDB tools installed successfully."

      - name: Install npm dependencies
        run: |
          echo "Installing npm dependencies..."
          cd backups  # Make sure you're in the backups directory
          npm install  # Ensure dependencies are installed from package.json inside backups
          echo "npm dependencies installed."

      - name: Run backup
        run: |
          echo "Starting backup process..."
          cd backups  # Make sure you're in the backups directory
          node makeBackup.js  # Run your backup script
          echo "Backup process completed."
