name: Deploy Backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install
        working-directory: server

      - name: Deploy Server
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.DO_HOST }}
          key: ${{ secrets.DO_SSH_KEY }}
          username: ${{ secrets.DO_USER }}
          script: |
            cd ~/scriptopia/server
            git pull
            npm install
            # Source NVM
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            # Restart the application
            pm2 restart server

            echo 'Backend Deployed Successfully!'
