name: Deploy Backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.DO_HOST }}
          key: ${{ secrets.DO_SSH_KEY }}
          username: ${{ secrets.DO_USER }}
          script: |
            cd ~/hoodly-backend
            git pull
            npm install
            pm2 restart all || pm2 restart 0
            echo 'Backend Deployed Successfully!'